services:
  postgres:
    image: postgres:latest
    container_name: weapon-database
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_DOCKER_PORT}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
